[project]
protostar-version = "0.8.1"
lib-path = "lib"
cairo-path = [
    "./lib/cairo_contracts/src",
    "src",
    "tests",
]

[contracts]
ERC3525MintableBurnable = ["./src/carbonable/erc3525/presets/ERC3525MintableBurnable.cairo"]
ERC3525SlotApprovable = ["./src/carbonable/erc3525/presets/ERC3525SlotApprovable.cairo"]
ERC3525SlotEnumerableMintableBurnable = ["./src/carbonable/erc3525/presets/ERC3525SlotEnumerableMintableBurnable.cairo"]
